# Numpy snippets

## Documentation

https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html

## Import directives

In [794]:
import numpy as np

## Create arrays

In [795]:
np.array([1, 2, 3])

array([1, 2, 3])

In [796]:
np.array([[1, 2, 3],[4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [797]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [798]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [799]:
np.ones(3)

array([ 1.,  1.,  1.])

In [800]:
np.ones((3, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [801]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [802]:
np.random.rand(3)

array([ 0.49236199,  0.56044653,  0.21394199])

In [803]:
np.random.rand(3, 4)

array([[ 0.26495936,  0.22345876,  0.22270719,  0.83656217],
       [ 0.24332518,  0.47431045,  0.91139059,  0.55369934],
       [ 0.00217221,  0.80595813,  0.89307862,  0.77351091]])

In [804]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [805]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [806]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [807]:
np.linspace(0., 2., 11)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ])

In [808]:
np.meshgrid([1, 2, 3], [4, 5, 6])

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]])]

## Dimension and shape

In [809]:
a = np.array([[1, 2, 3],[4, 5, 6]])

In [810]:
a.ndim

2

In [811]:
a.size

6

In [812]:
a.shape

(2, 3)

## Access elements

In [813]:
a = np.arange(6)

In [814]:
a

array([0, 1, 2, 3, 4, 5])

In [815]:
a[0]

0

In [816]:
a[-1]

5

In [817]:
a[1:4]

array([1, 2, 3])

In [818]:
a = np.array([[1, 2, 3, 4, 5, 6],[10, 20, 30, 40, 50, 60],[100, 200, 300, 400, 500, 600]])
a

array([[  1,   2,   3,   4,   5,   6],
       [ 10,  20,  30,  40,  50,  60],
       [100, 200, 300, 400, 500, 600]])

In [819]:
a[0,1]

2

In [820]:
a[1, :]

array([10, 20, 30, 40, 50, 60])

In [825]:
a[1, ::2]

array([10, 30, 50])

In [821]:
a[:, 1]

array([  2,  20, 200])

In [822]:
a[0:2, 2:4]

array([[ 3,  4],
       [30, 40]])

In [823]:
a[1:, 1:]

array([[ 20,  30,  40,  50,  60],
       [200, 300, 400, 500, 600]])

In [824]:
a[:-1, :-1]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

## Concatenate

In [691]:
a = np.zeros([2, 3])
b = np.ones([2, 3])

In [692]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [693]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [694]:
np.vstack([a, b])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [695]:
np.stack([a, b], 0)

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [696]:
np.hstack([a, b])

array([[ 0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  1.]])

In [697]:
np.stack([a, b], 1)

array([[[ 0.,  0.,  0.],
        [ 1.,  1.,  1.]],

       [[ 0.,  0.,  0.],
        [ 1.,  1.,  1.]]])

In [698]:
np.stack([a, b], 2)

array([[[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]],

       [[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]]])

In [699]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.tile(a, (2, 3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

## Reshape or transpose

In [700]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [701]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [702]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

## Linear algebra

In [703]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [704]:
np.dot(a, b)

140

In [705]:
a.dot(b)

140