# Numpy snippets

## Documentation

https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html

## Import directives

In [1]:
import numpy as np

## Create arrays

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([[1, 2, 3],[4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [5]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [6]:
np.ones(3)

array([ 1.,  1.,  1.])

In [7]:
np.ones((3, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [8]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [9]:
np.random.rand(3)

array([ 0.84917318,  0.30057741,  0.83780772])

In [10]:
np.random.rand(3, 4)

array([[ 0.23062845,  0.66007165,  0.73801174,  0.94256815],
       [ 0.84608622,  0.62716211,  0.14183244,  0.48830382],
       [ 0.09914072,  0.31579485,  0.56601881,  0.00650981]])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [14]:
np.linspace(0., 2., 11)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ])

In [15]:
np.meshgrid([1, 2, 3], [4, 5, 6])

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]])]

## Dimension and shape

In [16]:
a = np.array([[1, 2, 3],[4, 5, 6]])

In [17]:
a.ndim

2

In [18]:
a.size

6

In [19]:
a.shape

(2, 3)

## Access elements

In [20]:
a = np.arange(6)

In [21]:
a

array([0, 1, 2, 3, 4, 5])

In [22]:
a[0]

0

In [23]:
a[-1]

5

In [24]:
a[1:4]

array([1, 2, 3])

In [25]:
a = np.array([[1, 2, 3, 4, 5, 6],[10, 20, 30, 40, 50, 60],[100, 200, 300, 400, 500, 600]])
a

array([[  1,   2,   3,   4,   5,   6],
       [ 10,  20,  30,  40,  50,  60],
       [100, 200, 300, 400, 500, 600]])

In [26]:
a[0,1]

2

In [27]:
a[1, :]

array([10, 20, 30, 40, 50, 60])

In [28]:
a[1, ::2]

array([10, 30, 50])

In [29]:
a[:, 1]

array([  2,  20, 200])

In [30]:
a[0:2, 2:4]

array([[ 3,  4],
       [30, 40]])

In [31]:
a[1:, 1:]

array([[ 20,  30,  40,  50,  60],
       [200, 300, 400, 500, 600]])

In [32]:
a[:-1, :-1]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

## Filter

In [33]:
a = np.array([[1, 2, 3, 4, 5, 6],[10, 20, 30, 40, 50, 60],[100, 200, 300, 400, 500, 600]])
a

array([[  1,   2,   3,   4,   5,   6],
       [ 10,  20,  30,  40,  50,  60],
       [100, 200, 300, 400, 500, 600]])

### Boolean matrix whose i,jth element is (a_ij > 5)

In [34]:
(a>5)

array([[False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]], dtype=bool)

### Find the indices where (a > 0.5)

In [35]:
np.nonzero(a>5)

(array([0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]),
 array([5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]))

### a with elements greater than 5 zeroed out

In [36]:
a * (a<=5)

array([[1, 2, 3, 4, 5, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [37]:
a[a>5] = 0
a

array([[1, 2, 3, 4, 5, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## Concatenate

In [38]:
a = np.zeros([2, 3])
b = np.ones([2, 3])

In [39]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [40]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [41]:
np.vstack([a, b])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [42]:
np.stack([a, b], 0)

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [43]:
np.hstack([a, b])

array([[ 0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  1.]])

In [44]:
np.stack([a, b], 1)

array([[[ 0.,  0.,  0.],
        [ 1.,  1.,  1.]],

       [[ 0.,  0.,  0.],
        [ 1.,  1.,  1.]]])

In [45]:
np.stack([a, b], 2)

array([[[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]],

       [[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]]])

In [46]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.tile(a, (2, 3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

## Reshape or transpose

In [47]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [48]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

## Linear algebra

In [50]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [51]:
np.dot(a, b)

140

In [52]:
a.dot(b)

140