# Numpy snippets

## Documentation

https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html

## Import directives

In [65]:
import numpy as np

## Create arrays

In [66]:
np.array([1, 2, 3])

array([1, 2, 3])

In [67]:
np.array([[1, 2, 3],[4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

### Special matrices

In [68]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [69]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [70]:
np.ones(3)

array([ 1.,  1.,  1.])

In [71]:
np.ones((3, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [72]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### Arange

In [73]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [75]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

### Linspace and meshgrid

In [76]:
np.linspace(0., 2., 11)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ])

In [77]:
np.meshgrid([1, 2, 3], [4, 5, 6])

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]])]

### Random

#### Uniform distribution in [0, 1]

In [78]:
np.random.rand(3)

array([ 0.37885695,  0.96313609,  0.9068407 ])

In [79]:
np.random.rand(3, 4)

array([[ 0.70384601,  0.89943009,  0.38510103,  0.55226898],
       [ 0.46144723,  0.60141265,  0.6468736 ,  0.46535427],
       [ 0.98488747,  0.07808058,  0.90634955,  0.47932989]])

#### Poisson distribution

In [80]:
np.random.poisson(10, size=[3, 4])

array([[15,  8, 14,  8],
       [ 9,  8, 10,  5],
       [11,  8,  8,  9]])

#### Multivariate normal distribution

In [81]:
mu = np.array([0., 0.])
cov = np.array([[1., 0.],
                [1., 1.]])
num_points = 10

np.random.multivariate_normal(mu, cov, num_points)

array([[-0.48455121,  0.54448513],
       [ 0.35718818, -0.56703679],
       [ 1.73067121,  0.2580495 ],
       [ 0.60621822,  0.27541353],
       [-0.27997577, -0.03940646],
       [-0.18147983, -0.84294152],
       [-1.38406558, -0.62921696],
       [-0.53840374, -1.10677187],
       [ 0.35025304,  0.06950899],
       [ 1.47397406,  1.72858689]])

## Dimension and shape

In [82]:
a = np.array([[1, 2, 3],[4, 5, 6]])

In [83]:
a.ndim

2

In [84]:
a.size

6

In [85]:
a.shape

(2, 3)

## Access elements

In [86]:
a = np.arange(6)

In [87]:
a

array([0, 1, 2, 3, 4, 5])

In [88]:
a[0]

0

In [89]:
a[-1]

5

In [90]:
a[1:4]

array([1, 2, 3])

In [91]:
a = np.array([[1, 2, 3, 4, 5, 6],[10, 20, 30, 40, 50, 60],[100, 200, 300, 400, 500, 600]])
a

array([[  1,   2,   3,   4,   5,   6],
       [ 10,  20,  30,  40,  50,  60],
       [100, 200, 300, 400, 500, 600]])

In [92]:
a[0,1]

2

In [93]:
a[1, :]

array([10, 20, 30, 40, 50, 60])

In [94]:
a[1, ::2]

array([10, 30, 50])

In [95]:
a[:, 1]

array([  2,  20, 200])

In [96]:
a[0:2, 2:4]

array([[ 3,  4],
       [30, 40]])

In [97]:
a[1:, 1:]

array([[ 20,  30,  40,  50,  60],
       [200, 300, 400, 500, 600]])

In [98]:
a[:-1, :-1]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

## Filter

In [99]:
a = np.array([[1, 2, 3, 4, 5, 6],[10, 20, 30, 40, 50, 60],[100, 200, 300, 400, 500, 600]])
a

array([[  1,   2,   3,   4,   5,   6],
       [ 10,  20,  30,  40,  50,  60],
       [100, 200, 300, 400, 500, 600]])

### Boolean matrix whose i,jth element is (a_ij > 5)

In [100]:
(a>5)

array([[False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]], dtype=bool)

### Find the indices where (a > 0.5)

In [101]:
np.nonzero(a>5)

(array([0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]),
 array([5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]))

### Set or copy a with elements greater than 5 zeroed out

In [102]:
a * (a<=5)

array([[1, 2, 3, 4, 5, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [103]:
a[a>5] = 0
a

array([[1, 2, 3, 4, 5, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## Concatenate

In [104]:
a = np.zeros([2, 3])
b = np.ones([2, 3])

In [105]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [106]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [107]:
np.vstack([a, b])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [108]:
np.stack([a, b], 0)

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [109]:
np.hstack([a, b])

array([[ 0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  1.]])

In [110]:
np.stack([a, b], 1)

array([[[ 0.,  0.,  0.],
        [ 1.,  1.,  1.]],

       [[ 0.,  0.,  0.],
        [ 1.,  1.,  1.]]])

In [111]:
np.stack([a, b], 2)

array([[[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]],

       [[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]]])

In [112]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.tile(a, (2, 3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

## Reshape or transpose

In [113]:
a = np.array([[1, 2, 3], [4, 5, 6]])

### Transpose

In [114]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Flatten

In [115]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

### Reshape

In [116]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

#### Row vector to column vector

In [117]:
a.reshape([-1, 1])

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

#### Vector to matrix

In [118]:
a.reshape([2, 3])

array([[0, 1, 2],
       [3, 4, 5]])

In [119]:
a.reshape([3, 2])

array([[0, 1],
       [2, 3],
       [4, 5]])

## Linear algebra

In [120]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [121]:
np.dot(a, b)

140

In [122]:
a.dot(b)

140