# Numpy snippets

## Documentation

https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html

## Import directives

In [397]:
import numpy as np

## Create arrays

In [398]:
np.array([1, 2, 3])

array([1, 2, 3])

In [399]:
np.array([[1, 2, 3],[4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [400]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [401]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [402]:
np.ones(3)

array([ 1.,  1.,  1.])

In [403]:
np.ones((3, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [404]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [405]:
np.random.rand(3)

array([ 0.77283777,  0.6127424 ,  0.23367867])

In [406]:
np.random.rand(3, 4)

array([[ 0.59592917,  0.78873368,  0.03985085,  0.09772944],
       [ 0.26795206,  0.74509993,  0.42270229,  0.96082389],
       [ 0.20604007,  0.30761428,  0.57688855,  0.27930349]])

In [407]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [408]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [409]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [410]:
np.linspace(0., 2., 11)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ])

In [411]:
np.meshgrid([1, 2, 3], [4, 5, 6])

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]])]

## Dimension and shape

In [412]:
a = np.array([[1, 2, 3],[4, 5, 6]])

In [413]:
a.ndim

2

In [414]:
a.size

6

In [415]:
a.shape

(2, 3)

## Access elements

In [416]:
a = np.arange(6)

In [417]:
a

array([0, 1, 2, 3, 4, 5])

In [418]:
a[0]

0

In [419]:
a[-1]

5

In [420]:
a[1:4]

array([1, 2, 3])

In [421]:
a = np.array([[1, 2, 3, 4, 5, 6],[10, 20, 30, 40, 50, 60],[100, 200, 300, 400, 500, 600]])
a

array([[  1,   2,   3,   4,   5,   6],
       [ 10,  20,  30,  40,  50,  60],
       [100, 200, 300, 400, 500, 600]])

In [422]:
a[0,1]

2

In [423]:
a[1, :]

array([10, 20, 30, 40, 50, 60])

In [424]:
a[1, ::2]

array([10, 30, 50])

In [425]:
a[:, 1]

array([  2,  20, 200])

In [426]:
a[0:2, 2:4]

array([[ 3,  4],
       [30, 40]])

In [427]:
a[1:, 1:]

array([[ 20,  30,  40,  50,  60],
       [200, 300, 400, 500, 600]])

In [428]:
a[:-1, :-1]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

## Filter

In [429]:
a = np.array([[1, 2, 3, 4, 5, 6],[10, 20, 30, 40, 50, 60],[100, 200, 300, 400, 500, 600]])
a

array([[  1,   2,   3,   4,   5,   6],
       [ 10,  20,  30,  40,  50,  60],
       [100, 200, 300, 400, 500, 600]])

### Boolean matrix whose i,jth element is (a_ij > 5)

In [430]:
(a>5)

array([[False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]], dtype=bool)

### Find the indices where (a > 0.5)

In [431]:
np.nonzero(a>5)

(array([0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]),
 array([5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]))

### a with elements greater than 5 zeroed out

In [432]:
a * (a<=5)

array([[1, 2, 3, 4, 5, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [433]:
a[a>5] = 0
a

array([[1, 2, 3, 4, 5, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## Concatenate

In [434]:
a = np.zeros([2, 3])
b = np.ones([2, 3])

In [435]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [436]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [437]:
np.vstack([a, b])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [438]:
np.stack([a, b], 0)

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [439]:
np.hstack([a, b])

array([[ 0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  1.]])

In [440]:
np.stack([a, b], 1)

array([[[ 0.,  0.,  0.],
        [ 1.,  1.,  1.]],

       [[ 0.,  0.,  0.],
        [ 1.,  1.,  1.]]])

In [441]:
np.stack([a, b], 2)

array([[[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]],

       [[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]]])

In [442]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.tile(a, (2, 3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

## Reshape or transpose

In [443]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [444]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [445]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

## Linear algebra

In [446]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [447]:
np.dot(a, b)

140

In [448]:
a.dot(b)

140