# Numpy snippets

## Documentation

This notebook is inspired by the following page: https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html

## Import directives

In [1]:
import numpy as np

## Create arrays

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([[1, 2, 3],[4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

### Special matrices

In [4]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [5]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [6]:
np.ones(3)

array([ 1.,  1.,  1.])

In [7]:
np.ones((3, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [8]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### Arange

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

### Linspace and meshgrid

In [12]:
np.linspace(0., 2., 11)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ])

In [13]:
np.meshgrid([1, 2, 3], [4, 5, 6])

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]])]

### Random

#### Uniform distribution in [0, 1]

In [14]:
np.random.rand(3)

array([ 0.88452189,  0.743751  ,  0.67150083])

In [15]:
np.random.rand(3, 4)

array([[ 0.16607954,  0.82464848,  0.51832928,  0.56797482],
       [ 0.36423298,  0.30763295,  0.90804496,  0.98225809],
       [ 0.11315311,  0.36398201,  0.91947533,  0.759239  ]])

#### Poisson distribution

In [16]:
np.random.poisson(10, size=[3, 4])

array([[10,  6, 18,  3],
       [ 5,  6,  9,  8],
       [ 5,  9, 10, 10]])

#### Multivariate normal distribution

In [17]:
mu = np.array([0., 0.])
cov = np.array([[1., 0.],
                [1., 1.]])
num_points = 10

np.random.multivariate_normal(mu, cov, num_points)

array([[ 0.98831211,  0.20093651],
       [ 0.13718739,  0.04717609],
       [-1.46159446, -0.22605992],
       [ 0.4875862 , -1.54703699],
       [ 1.76865817,  1.80538568],
       [-0.48778403, -1.2793686 ],
       [ 1.45057686,  2.81011708],
       [ 0.82690694, -0.93197129],
       [ 0.59192186,  1.01667719],
       [ 0.6607188 , -0.70062132]])

## Dimension and shape

In [18]:
a = np.array([[1, 2, 3],[4, 5, 6]])

In [19]:
a.ndim

2

In [20]:
a.size

6

In [21]:
a.shape

(2, 3)

## Convert

In [22]:
l = [[1, 2, 3],[4, 5, 6]]
a = np.array([[1, 2, 3],[4, 5, 6]])

### Python list to Numpy array

In [23]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

### Numpy array to Python list

In [24]:
a.tolist()

[[1, 2, 3], [4, 5, 6]]

## Access elements

In [25]:
a = np.arange(6)

In [26]:
a

array([0, 1, 2, 3, 4, 5])

In [27]:
a[0]

0

In [28]:
a[-1]

5

In [29]:
a[1:4]

array([1, 2, 3])

In [30]:
a = np.array([[1, 2, 3, 4, 5, 6],[10, 20, 30, 40, 50, 60],[100, 200, 300, 400, 500, 600]])
a

array([[  1,   2,   3,   4,   5,   6],
       [ 10,  20,  30,  40,  50,  60],
       [100, 200, 300, 400, 500, 600]])

In [31]:
a[0,1]

2

In [32]:
a[1, :]

array([10, 20, 30, 40, 50, 60])

In [33]:
a[1, ::2]

array([10, 30, 50])

In [34]:
a[:, 1]

array([  2,  20, 200])

In [35]:
a[0:2, 2:4]

array([[ 3,  4],
       [30, 40]])

In [36]:
a[1:, 1:]

array([[ 20,  30,  40,  50,  60],
       [200, 300, 400, 500, 600]])

In [37]:
a[:-1, :-1]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

## Filter

In [38]:
a = np.array([[1, 2, 3, 4, 5, 6],[10, 20, 30, 40, 50, 60],[100, 200, 300, 400, 500, 600]])
a

array([[  1,   2,   3,   4,   5,   6],
       [ 10,  20,  30,  40,  50,  60],
       [100, 200, 300, 400, 500, 600]])

### Boolean matrix whose i,jth element is (a_ij > 5)

In [39]:
(a>5)

array([[False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]], dtype=bool)

### Find the indices where (a > 0.5)

In [40]:
np.nonzero(a>5)

(array([0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]),
 array([5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]))

### Set or copy a with elements greater than 5 zeroed out

In [41]:
a * (a<=5)

array([[1, 2, 3, 4, 5, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [42]:
a[a>5] = 0
a

array([[1, 2, 3, 4, 5, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## Concatenate

In [43]:
a = np.zeros([2, 3])
b = np.ones([2, 3])

In [44]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [45]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [46]:
np.vstack([a, b])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [47]:
np.stack([a, b], 0)

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [48]:
np.hstack([a, b])

array([[ 0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  1.]])

In [49]:
np.stack([a, b], 1)

array([[[ 0.,  0.,  0.],
        [ 1.,  1.,  1.]],

       [[ 0.,  0.,  0.],
        [ 1.,  1.,  1.]]])

In [50]:
np.stack([a, b], 2)

array([[[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]],

       [[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  1.]]])

In [51]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.tile(a, (2, 3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

## Reshape or transpose

In [52]:
a = np.array([[1, 2, 3], [4, 5, 6]])

### Transpose

In [53]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Flatten

In [54]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

### Reshape

In [55]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

#### Row vector to column vector

In [56]:
a.reshape([-1, 1])

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

#### Vector to matrix

In [57]:
a.reshape([2, 3])

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
a.reshape([3, 2])

array([[0, 1],
       [2, 3],
       [4, 5]])

## Linear algebra

In [59]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [60]:
np.dot(a, b)

140

In [61]:
a.dot(b)

140